name: Clean OpenAPI Specs

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  clean-specs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Redocly CLI
      run: npm install -g @redocly/cli
      
    - name: Create Redocly config
      run: |
        cat > redocly.yaml << EOF
        apis:
          main:
            root: ./openapi.yaml
        decorators:
          remove-x-internal:
            remove-x-internal: true
        EOF
        
    - name: Create output directory
      run: mkdir -p ./cleaned-specs
        
    - name: Clean OpenAPI specs (remove x-internal)
      run: |
        # Find OpenAPI spec files (exclude node_modules and common non-spec directories)
        find . -path "*/node_modules" -prune -o -path "*/.git" -prune -o \
          \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) -print | \
          grep -E "(openapi|swagger|api)" | \
          while read file; do
            echo "Checking $file for OpenAPI specification..."
            # Check if file contains OpenAPI/Swagger indicators
            if grep -q -E "(openapi:|swagger:|\"openapi\":|\"swagger\":)" "$file" 2>/dev/null; then
              echo "Processing OpenAPI spec: $file"
              filename=$(basename "$file")
              redocly bundle "$file" --output "./cleaned-specs/$filename" --config redocly.yaml
            else
              echo "Skipping $file (not an OpenAPI specification)"
            fi
          done
        
    # - name: Validate cleaned specs
    #   run: |
    #     find ./cleaned-specs -name "*.yaml" -o -name "*.yml" -o -name "*.json" | while read file; do
    #       echo "Validating $file"
    #       redocly lint "$file"
    #     done
        
    - name: Upload cleaned specs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cleaned-openapi-specs
        path: ./cleaned-specs/
        retention-days: 30
